"""Assembly export (PLAN.md Layer 8: Remotion -> FFmpeg encode).

Two output paths from the same EDL:
1. remotion_props.json - consumed by the Remotion project in remotion/
   (npx remotion render Documentary --props=<path>). Handles Ken Burns on
   stills, DRAMATIZATION labels, and frame-accurate timing at 30fps.
2. assemble_ffmpeg.sh - dependency-free fallback that cuts/concats the same
   timeline with plain FFmpeg (stills looped, videos trimmed) and muxes the
   mastered narration. Used on boxes where Node isn't available.

Both are deterministic renderings OF the EDL - the EDL stays the single
source of truth (M4's QC failures map back to EDL timestamps).
"""

from __future__ import annotations

import json
import shlex
from pathlib import Path

FPS = 30
WIDTH, HEIGHT = 1920, 1080

_STILL_EXT = {".jpg", ".jpeg", ".png", ".webp", ".tif", ".tiff", ".gif", ".bmp"}


def export_props(edl: dict, audio_path: Path | None, media_paths: dict[str, str],
                 out_path: Path) -> dict:
    """media_paths: asset_id -> local media file (from the M2 library /
    generated renders). Missing media exports as a slate so the render never
    silently drops an event."""
    sequences = []
    for e in edl["events"]:
        src = media_paths.get(e["asset_id"])
        dur = e["video_out"] - e["video_in"]
        sequences.append({
            "eventId": e["event_id"],
            "src": src,                       # null -> slate with shot metadata
            "missing": src is None,
            "isStill": _is_still(src, e["kind"]),
            "fromFrame": round(e["video_in"] * FPS),
            "durationFrames": max(1, round(dur * FPS)),
            "kind": e["kind"],
            "cutStyle": e["cut_style"],
            "hold": e["hold"],
            "ambienceSwell": e["ambience_swell"],
            "label": e["label"],              # "DRAMATIZATION" or null
            "attribution": e["attribution"],
        })
    props = {
        "fps": FPS,
        "width": WIDTH,
        "height": HEIGHT,
        "durationFrames": max(1, round(edl["duration_s"] * FPS)),
        "narrationSrc": str(audio_path) if audio_path else None,
        "sequences": sequences,
    }
    out_path.write_text(json.dumps(props, indent=2), encoding="utf-8")
    return props


def write_ffmpeg_fallback(edl: dict, audio_path: Path | None,
                          media_paths: dict[str, str], out_script: Path) -> Path:
    """Emit a self-contained shell script: one normalized segment per event,
    concat, mux narration. Events without media render a labeled slate."""
    lines = ["#!/usr/bin/env bash",
             "# Generated by pipeline.edit.remotion_export - do not hand-edit.",
             "set -euo pipefail",
             'W=$(mktemp -d); trap \'rm -rf "$W"\' EXIT', ""]
    concat = []
    for i, e in enumerate(edl["events"]):
        src = media_paths.get(e["asset_id"])
        dur = max(0.1, e["video_out"] - e["video_in"])
        seg = f'"$W"/seg{i:03d}.mp4'
        vf = (f"scale={WIDTH}:{HEIGHT}:force_original_aspect_ratio=decrease,"
              f"pad={WIDTH}:{HEIGHT}:(ow-iw)/2:(oh-ih)/2,setsar=1,fps={FPS}")
        if src is None:
            text = f"MISSING {e['shot_id']}"
            lines.append(
                f"ffmpeg -y -f lavfi -i color=c=0x101010:s={WIDTH}x{HEIGHT}:r={FPS} "
                f"-t {dur:.3f} -vf \"drawtext=text={shlex.quote(text)}:fontcolor=white:"
                f"fontsize=48:x=(w-tw)/2:y=(h-th)/2\" -an {seg}")
        elif _is_still(src, e["kind"]):
            lines.append(
                f"ffmpeg -y -loop 1 -t {dur:.3f} -i {shlex.quote(src)} "
                f"-vf \"{vf}\" -an -pix_fmt yuv420p {seg}")
        else:
            lines.append(
                f"ffmpeg -y -t {dur:.3f} -i {shlex.quote(src)} "
                f"-vf \"{vf}\" -an -pix_fmt yuv420p {seg}")
        if e["label"]:
            # Burn the dramatization label in a second, simpler pass.
            lab = f'"$W"/seg{i:03d}l.mp4'
            lines.append(
                f"ffmpeg -y -i {seg} -vf \"drawtext=text={e['label']}:fontcolor=white@0.9:"
                f"fontsize=28:box=1:boxcolor=black@0.5:boxborderw=8:x=32:y=h-th-32\" "
                f"-an {lab} && mv {lab} {seg}")
        concat.append(seg)
    lines.append("")
    lines.append('printf "file \'%s\'\\n" ' + " ".join(concat) + ' > "$W"/list.txt')
    audio_in = f"-i {shlex.quote(str(audio_path))} " if audio_path else ""
    audio_map = "-map 0:v -map 1:a -c:a aac -shortest " if audio_path else ""
    lines.append(
        f'ffmpeg -y -f concat -safe 0 -i "$W"/list.txt {audio_in}'
        f"-c:v libx264 -preset medium -crf 18 {audio_map}assembled.mp4")
    lines.append('echo "DONE: assembled.mp4"')
    out_script.write_text("\n".join(lines) + "\n", encoding="utf-8")
    out_script.chmod(0o755)
    return out_script


def _is_still(src: str | None, kind: str) -> bool:
    if src is None:
        return kind != "footage"
    return Path(src).suffix.lower() in _STILL_EXT
